name: "jenkine bridge"
description: "trigger jenkine pipeline"

runs:
  using: "composite"
  steps:
    - name: Env
      run: export

    - name: Install Client
      run: |
        wget --quiet https://repo.peeweep.de/tmp/jenkins-bridge-client -O /usr/bin/jenkins-bridge-client
        chmod +x -v /usr/bin/jenkins-bridge-client

    - name: Print log
      env:
        BRIDGE_TOKEN: ${{ secrets.BridgeToken }}

    - name: Download Artifacts
      run: |
        jenkins-bridge-client -token "$BRIDGE_TOKEN" -downloadArtifacts 1
        ls -lh ./artifacts

    - uses: peeweep-test/upload-artifact@single-artifact-upload
      with:
        path: ./artifacts/*.deb
        single-archive: "false"
