name: "jenkine bridge"
description: "trigger jenkine pipeline"
inputs:
  token: # id of input
    description: "api auth token"
    required: true
    default: ""
runs:
  using: "composite"
  steps:
    - name: Env
      shell: bash
      run: export

    - name: Install Client
      shell: bash
      run: |
        sudo wget --quiet https://repo.peeweep.de/tmp/jenkins-bridge-client -O /usr/bin/jenkins-bridge-client
        sudo chmod +x -v /usr/bin/jenkins-bridge-client

    - name: Print log
      shell: bash
      env:
        BRIDGE_TOKEN: ${{ inputs.token }}
      run: jenkins-bridge-client -token "$BRIDGE_TOKEN" -printlog 1

    - name: Download Artifacts
      shell: bash
      env:
        BRIDGE_TOKEN: ${{ inputs.token }}
      run: jenkins-bridge-client -token "$BRIDGE_TOKEN" -downloadArtifacts 1

    - name: List Artifacts
      shell: bash
      run: ls -lh ./artifacts

    - uses: peeweep-test/upload-artifact@single-artifact-upload
      with:
        path: ./artifacts/*.deb
        single-archive: "false"
