name: "jenkine bridge"
description: "trigger jenkine pipeline"
inputs:
  token: # id of input
    description: "api auth token"
    required: true
    default: ""
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Print Env
      shell: bash
      run: |
        echo ::group::print environment
        export
        echo ::endgroup::

    - name: Install Client
      shell: bash
      run: |
        echo ::group::install client
        sudo wget --quiet https://repo.peeweep.de/tmp/jenkins-bridge-client -O /usr/bin/jenkins-bridge-client
        sudo chmod +x -v /usr/bin/jenkins-bridge-client
        echo ::endgroup::

    - name: Print log
      shell: bash
      env:
        BRIDGE_TOKEN: ${{ inputs.token }}
      run: |
        echo ::group::Build Output
        jenkins-bridge-client -token "$BRIDGE_TOKEN" -printlog 1
        echo ::endgroup::

    - name: Download Artifacts
      shell: bash
      env:
        BRIDGE_TOKEN: ${{ inputs.token }}
      run: |
        echo ::group::Download Artifacts
        jenkins-bridge-client -token "$BRIDGE_TOKEN" -downloadArtifacts 1
        ls -lh ./artifacts
        echo ::endgroup::

    - uses: peeweep-test/upload-artifact@single-artifact-upload
      with:
        path: ./artifacts/*.deb
        single-archive: "false"
